export const PORTAL_CONFIG = {
  nobroker: {
    displayName: 'NoBroker',
    dotColor: 'bg-[var(--color-portal-nobroker-green)]',
    textColor: 'text-[var(--color-portal-nobroker-green)]',
    badgeBg: 'bg-[var(--color-portal-nobroker-green)]/10 dark:bg-[var(--color-portal-nobroker-green)]/20',
    badgeBorder: 'border-[var(--color-portal-nobroker-green)]/30',
    ctaBg: 'bg-[var(--color-portal-nobroker-green)] hover:bg-[var(--color-portal-nobroker-green)]/90 shadow-[0_0_12px_rgba(16,185,129,0.2)]',
    focusRing: 'focus:ring-[var(--color-portal-nobroker-green)]',
  },
  '99acres': {
    displayName: '99acres',
    dotColor: 'bg-[var(--color-portal-acres-blue)]',
    textColor: 'text-[var(--color-portal-acres-blue)]',
    badgeBg: 'bg-[var(--color-portal-acres-blue)]/10 dark:bg-[var(--color-portal-acres-blue)]/20',
    badgeBorder: 'border-[var(--color-portal-acres-blue)]/30',
    ctaBg: 'bg-[var(--color-portal-acres-blue)] hover:bg-[var(--color-portal-acres-blue)]/90 shadow-[0_0_12px_rgba(2,132,199,0.2)]',
    focusRing: 'focus:ring-[var(--color-portal-acres-blue)]',
  },
  magicbricks: {
    displayName: 'MagicBricks',
    dotColor: 'bg-[var(--color-portal-magicbricks)]',
    textColor: 'text-[var(--color-portal-magicbricks)]',
    badgeBg: 'bg-[var(--color-portal-magicbricks)]/10 dark:bg-[var(--color-portal-magicbricks)]/20',
    badgeBorder: 'border-[var(--color-portal-magicbricks)]/30',
    ctaBg: 'bg-[var(--color-portal-magicbricks)] hover:bg-[var(--color-portal-magicbricks)]/90 shadow-[0_0_12px_rgba(42,157,143,0.2)]',
    focusRing: 'focus:ring-[var(--color-portal-magicbricks)]',
  },
  housing: {
    displayName: 'Housing.com',
    dotColor: 'bg-[var(--color-portal-housing)]',
    textColor: 'text-[var(--color-portal-housing)]',
    badgeBg: 'bg-[var(--color-portal-housing)]/10 dark:bg-[var(--color-portal-housing)]/20',
    badgeBorder: 'border-[var(--color-portal-housing)]/30',
    ctaBg: 'bg-[var(--color-portal-housing)] hover:bg-[var(--color-portal-housing)]/90 shadow-[0_0_12px_rgba(69,123,157,0.2)]',
    focusRing: 'focus:ring-[var(--color-portal-housing)]',
  },
  squareyards: {
    displayName: 'Square Yards',
    dotColor: 'bg-[var(--color-portal-squareyards)]',
    textColor: 'text-[var(--color-portal-squareyards)]',
    badgeBg: 'bg-[var(--color-portal-squareyards)]/10 dark:bg-[var(--color-portal-squareyards)]/20',
    badgeBorder: 'border-[var(--color-portal-squareyards)]/30',
    ctaBg: 'bg-[var(--color-portal-squareyards)] hover:bg-[var(--color-portal-squareyards)]/90 shadow-[0_0_12px_rgba(106,76,147,0.2)]',
    focusRing: 'focus:ring-[var(--color-portal-squareyards)]',
  },
  default: {
    displayName: 'Portal',
    dotColor: 'bg-zinc-400',
    textColor: 'text-zinc-600 dark:text-zinc-400',
    badgeBg: 'bg-zinc-100 dark:bg-zinc-800',
    badgeBorder: 'border-zinc-200 dark:border-zinc-700',
    ctaBg: 'bg-zinc-700 hover:bg-zinc-800 focus:ring-zinc-500',
    focusRing: 'focus:ring-zinc-500',
  },
} as const

export const PRIORITY_LABELS: Record<string, string> = {
  nobroker: 'Best for Rent',
  '99acres': 'Best for Buy',
  default: 'Priority Choice',
} as const
